CREATE TABLE RefreshToken(
    [Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserId BIGINT NOT NULL,
    [TokenHash] NVARCHAR(255) NOT NULL,
    [ExpiryDate] DATETIME NOT NULL
    FOREIGN KEY (UserId) REFERENCES [User](UserId) ON DELETE CASCADE
)
